quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=tarefas
quarkus.datasource.password=tarefas
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tarefas_db
quarkus.hibernate-orm.database.generation=none
